In [1]:
import torchvision
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\app\anaconda\envs\pytorch\lib\site-packages\torch\lib\cudnn_adv_train64_8.dll" or one of its dependencies.

In [12]:
test_data = torchvision.datasets.CIFAR10("./dataset",train=False,transform=torchvision.transforms.ToTensor())
# num_workers=0 采用主进程加载,drop_last=False不舍弃除不尽的牌
test_loader = DataLoader(dataset= test_data,batch_size=64,shuffle=False,num_workers=0,drop_last=True)


In [3]:
# 查看数据(测试集的第一张图片)
img,target = test_data[0]
print(img.shape)
print(target)

torch.Size([3, 32, 32])
3


In [4]:
# 查看前5组，每组4张图片
j = 1
for data in test_loader:
    if j==6:
        break
    img1,target1 = data
    print(img1.shape)
    print(target1)
    j+=1

torch.Size([64, 3, 32, 32])
tensor([4, 0, 0, 1, 1, 5, 3, 2, 5, 2, 1, 8, 2, 3, 3, 3, 2, 5, 6, 6, 4, 7, 5, 6,
        5, 5, 6, 1, 1, 3, 5, 4, 5, 1, 7, 6, 8, 4, 8, 9, 8, 0, 5, 6, 0, 6, 4, 0,
        0, 9, 1, 3, 9, 4, 1, 9, 5, 0, 4, 7, 4, 0, 6, 0])
torch.Size([64, 3, 32, 32])
tensor([7, 8, 1, 4, 9, 1, 8, 5, 9, 8, 4, 8, 0, 1, 9, 7, 3, 3, 5, 4, 2, 4, 3, 4,
        7, 8, 2, 5, 1, 6, 7, 2, 6, 8, 3, 9, 1, 2, 2, 4, 9, 0, 2, 4, 6, 2, 2, 6,
        8, 8, 8, 8, 3, 6, 1, 8, 5, 8, 5, 2, 8, 3, 5, 8])
torch.Size([64, 3, 32, 32])
tensor([1, 5, 0, 8, 7, 6, 9, 2, 7, 9, 8, 7, 5, 8, 2, 8, 3, 7, 6, 8, 1, 2, 6, 6,
        1, 2, 1, 8, 1, 7, 3, 7, 6, 2, 8, 8, 2, 8, 9, 2, 0, 2, 7, 5, 3, 0, 7, 9,
        5, 2, 4, 5, 5, 0, 5, 1, 9, 2, 8, 5, 2, 7, 4, 1])
torch.Size([64, 3, 32, 32])
tensor([7, 8, 4, 1, 1, 5, 7, 8, 5, 5, 6, 6, 5, 1, 2, 1, 9, 7, 4, 2, 2, 3, 0, 7,
        2, 5, 3, 2, 5, 2, 8, 0, 4, 7, 1, 0, 9, 4, 7, 3, 0, 1, 0, 9, 5, 6, 6, 1,
        1, 6, 3, 6, 6, 8, 2, 4, 5, 9, 0, 4, 8, 3, 9, 8])
torch.Size([64, 3, 3

In [13]:
# 显示出来 （将batch_size改为64）
writer = SummaryWriter("dataloader")
step = 0
for echo in range(2):
    for data in test_loader:
        imgs,targets = data
        writer.add_images("echo_"+str(echo),imgs,step)
        step+=1
writer.close()