In [1]:
import torch

In [4]:
input = torch.tensor([
    [1,2,0,3,1],
    [0,1,2,3,1],
    [1,2,1,0,0],
    [5,2,3,1,1],
    [2,1,0,1,1]
])
print(input)
print(input.shape)

tensor([[1, 2, 0, 3, 1],
        [0, 1, 2, 3, 1],
        [1, 2, 1, 0, 0],
        [5, 2, 3, 1, 1],
        [2, 1, 0, 1, 1]])
torch.Size([5, 5])


In [5]:
kernel = torch.tensor([
    [1,2,1],
    [0,1,0],
    [2,1,0]
])
print(kernel)
print(kernel.shape)

tensor([[1, 2, 1],
        [0, 1, 0],
        [2, 1, 0]])
torch.Size([3, 3])


In [6]:
# 改变形状
input = torch.reshape(input,(1,1,5,5))
kernel = torch.reshape(kernel,(1,1,3,3))
print(input.shape)
print(kernel.shape)

torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])


In [10]:
# 卷积
import torch.nn.functional as F
# 步长为1
output = F.conv2d(input,kernel,stride=1)
print(output)
print(output.shape)
# 填充设为1
output_1 = F.conv2d(input,kernel,stride=1,padding=1)
print(output_1)
print(output_1.shape)

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])
torch.Size([1, 1, 3, 3])
tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])
torch.Size([1, 1, 5, 5])


In [11]:
# 步长为2
output2 = F.conv2d(input,kernel,stride=2)
print(output2)
print(output2.shape)
# 填充设为1
output_2 = F.conv2d(input,kernel,stride=2,padding=1)
print(output_1)
print(output_1.shape)

tensor([[[[10, 12],
          [13,  3]]]])
torch.Size([1, 1, 2, 2])
tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])
torch.Size([1, 1, 5, 5])
