In [21]:
import torch
from torch.nn import L1Loss
from torch import nn
import torchvision
from torch.utils.data import DataLoader

In [10]:
input = torch.tensor([1,2,3],dtype=torch.float32)
target = torch.tensor([1,2,5],dtype=torch.float32)
# 方法一
# input = torch.reshape(input,(1,1,1,3))
# target = torch.reshape(target,(1,1,1,3))
# 方法二
input = input.view(1,1,1,-1)
target = target.view(1,1,1,-1)


# 计算误差（l1）
loss = L1Loss(reduction='sum')# 默认的是求平均
result = loss(input,target)
print(result)




tensor(2.)


In [13]:
# l2，均方误差(回归问题）
loss  = nn.MSELoss()
result = loss(input,target)
print(result)

tensor(1.3333)


In [16]:
# 交叉熵（分类问题）
x = torch.tensor([0.1,0.2,0.3])
y = torch.tensor([1])
x = torch.reshape(x,(1,3))
loss = nn.CrossEntropyLoss()
result = loss(x,y)
print(result)

torch.Size([3])
tensor(1.1019)


In [24]:
# 运用
dataset = torchvision.datasets.CIFAR10("./dataset",train=False,transform=torchvision.transforms.ToTensor(),download=False)
dataloader = DataLoader(dataset,batch_size=1)

In [25]:
class Tutui2(nn.Module):
    def __init__(self):
        super(Tutui2,self).__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3,32,5,padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,32,5,padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,64,5,padding=2),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(1024,64),
            nn.Linear(64,10)
        )
    def forward(self,x):
        x = self.model(x)
        return x

In [27]:
loss = nn.CrossEntropyLoss()
tutui = Tutui2()
# 设置优化器(随机梯度下降)
'''
优化器的作用包括：2
参数更新：优化器根据损失函数的梯度信息来更新模型的参数。
加速收敛：优化器可以帮助模型更快地收敛到最优解。
避免局部极小值：优化器能够帮助模型跳出局部极小值，以寻找全局最优解。
处理非凸函数：在深度学习中，损失函数通常是高度非凸的，这意味着存在多个局部最优解。
自适应学习率：一些优化器（如Adam）可以根据参数的梯度自适应地调整学习率，从而在不同参数和时间步骤上使用不同的学习率，提高了优化的稳定性和适应性。

'''
optim = torch.optim.SGD(tutui.parameters(),lr=0.01)
for data in dataloader:
    img , target = data
    output = tutui(img)
    result = loss(output,target)
    # 把可调节参数的梯度调为0
    optim.zero_grad()
    

tensor([[ 0.1319, -0.0168,  0.0985, -0.0699,  0.0079, -0.0532, -0.1497, -0.0225,
         -0.1759, -0.0853]], grad_fn=<AddmmBackward0>)
tensor([3])
tensor(2.3433, grad_fn=<NllLossBackward0>)
tensor([[ 0.1264, -0.0070,  0.0878, -0.0547, -0.0043, -0.0466, -0.1407, -0.0363,
         -0.1801, -0.0912]], grad_fn=<AddmmBackward0>)
tensor([8])
tensor(2.4520, grad_fn=<NllLossBackward0>)
tensor([[ 0.1242, -0.0111,  0.1009, -0.0660, -0.0027, -0.0531, -0.1375, -0.0224,
         -0.1646, -0.0893]], grad_fn=<AddmmBackward0>)
tensor([8])
tensor(2.4389, grad_fn=<NllLossBackward0>)
tensor([[ 0.1355, -0.0010,  0.0924, -0.0601, -0.0014, -0.0609, -0.1541, -0.0290,
         -0.1840, -0.0982]], grad_fn=<AddmmBackward0>)
tensor([0])
tensor(2.1355, grad_fn=<NllLossBackward0>)
tensor([[ 0.1277, -0.0064,  0.0962, -0.0709,  0.0040, -0.0477, -0.1446, -0.0256,
         -0.1735, -0.0970]], grad_fn=<AddmmBackward0>)
tensor([6])
tensor(2.4176, grad_fn=<NllLossBackward0>)
tensor([[ 0.1299, -0.0051,  0.1054, -0.0662, 